### PR TITLE
feat: migrate to IntelliJ Platform Gradle Plugin

### LINKED ISSUE #74: Only old version of plugin is available in latest IDEA version
After upgrading to 2024.2 IDEA reinstalls biome plugin to 1.0.0 version, removing all fixes introduced later

image
Seems since 1.0.2 last version was hardened

### PR DESCRIPTION
**Pull request by bc-m**
This merge request migrates this plugin from [Gradle IntelliJ Plugin (1.x)](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html) to [IntelliJ Platform Gradle Plugin (2.x)](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html) to add compatibility with IntelliJ IDEs 2024.2+.

https://plugins.jetbrains.com/docs/intellij/api-notable-list-2024.html

Closes #74 #75

### CODE REVIEW

**Comment by bc-m** [comment]
@ematipico Can you please review this when you have time? Thank you! :)

**Review by ematipico — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
@bc-m Can I release a new version after this PR is merged?

**Comment by bc-m** [comment]
> @bc-m Can I release a new version after this PR is merged?

"It works on my machine" 😄 

I couldn't or didn't know how to test the release steps. These were adjusted in [build.gradle.kts](https://github.com/biomejs/biome-intellij/pull/77/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06). I have made the changes bases on the official [plugin-template](https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/build.gradle.kts). 

Can you try a nightly release at first?

**Comment by ematipico** [comment]
Done! I triggered the workflow

**Comment by bc-m** [comment]
> Done! I triggered the workflow

And... it failed! 😞 I have build it locally and the output file is named `intellij-biome-valueof(GradlePropertyValueSource).zip`, which seems to be incorrect. I'll check it out.

**Pull request merged**
